## Run tests with most recent golang version to take advantage of any perf
## improvements.
image: golang:1.13

stages:
  - lint
  - test
  - deploy
 
lint:
  stage: lint
  before_script:
    - mkdir -p .cache/gocache
    - export PATH=$PATH:$CI_PROJECT_DIR/.cache/bin/
    - export GOPATH="$CI_PROJECT_DIR/.cache"
    - export GOCACHE=$CI_PROJECT_DIR/.cache/gocache
    ## This is the recommended way to install golang-ci lint.
    - wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.23.8
    - apt-get update
    - apt-get -y install python3-pip
    - pip3 install codespell  

  cache:
    key: lint-cache
    paths:
      - .cache
  script: 
    - ./bin/golangci-lint run -c .golangci.yml ./...
    ## - make lint-analysis
    ## - make markdown-spellcheck
    - make test

node-api-tests:
  stage: test
  except:
    - schedules
  before_script:
    - mkdir -p .cache/gocache
    - export PATH=$PATH:$CI_PROJECT_DIR/.cache/bin/
    - export GOPATH=$CI_PROJECT_DIR/.cache
    - export GOCACHE=$CI_PROJECT_DIR/.cache/gocache    
  cache:
    key: legacy-tests-cache
    paths:
      - .cache    
  artifacts:
    name: "SiaTesting-$CI_JOB_NAME"
    paths:
      - $CI_PROJECT_DIR/SiaTesting
      - $CI_PROJECT_DIR/cover/cover.out
    when: always
  script:
    - make test-long pkgs="./node ./node/api ./node/api/server" run=.
    - cp -R /tmp/SiaTesting $CI_PROJECT_DIR/SiaTesting

package-tests:
  stage: test
  except:
    - schedules
  artifacts:
    name: "SiaTesting-$CI_JOB_NAME"
    paths:
      - $CI_PROJECT_DIR/SiaTesting
      - $CI_PROJECT_DIR/cover/cover.out
    when: always
  script:
    - make test-long run=. pkgs="./build ./cmd/spc ./cmd/spd ./compatibility ./crypto ./encoding ./modules ./modules/consensus ./modules/explorer ./modules/gateway ./modules/host ./modules/host/contractmanager ./modules/renter ./modules/renter/contractor ./modules/renter/hostdb ./modules/renter/hostdb/hosttree ./modules/renter/proto ./modules/renter/siadir ./modules/renter/siafile ./modules/miner ./modules/wallet ./modules/transactionpool ./persist ./sync ./types"
    - cp -R /tmp/SiaTesting $CI_PROJECT_DIR/SiaTesting

siatest-tests:
  stage: test
  except:
    - schedules
  artifacts:
    name: "SiaTesting-$CI_JOB_NAME"
    paths:
      - $CI_PROJECT_DIR/SiaTesting
      - $CI_PROJECT_DIR/cover/cover.out
    when: always
  script:
    - make test-long run=. pkgs="./siatest ./siatest/consensus ./siatest/daemon ./siatest/gateway ./siatest/miner ./siatest/transactionpool ./siatest/wallet"
    - cp -R /tmp/SiaTesting $CI_PROJECT_DIR/SiaTesting

siatest-renter-tests:
  stage: test
  except:
    - schedules
  before_script:
    - mkdir -p .cache/gocache
    - export PATH=$PATH:$CI_PROJECT_DIR/.cache/bin/
    - export GOPATH=$CI_PROJECT_DIR/.cache
    - export GOCACHE=$CI_PROJECT_DIR/.cache/gocache    
    - apt-get update
    - apt-get install -y fuse    
    
  cache:
    key: siatest-renter-tests-cache
    paths:
      - .cache
  script:
    - make test-long run=. pkgs="./siatest/renterhost ./siatest/renter/hostdb ./siatest/renter/contractor ./siatest/renter"

legacy-tests-nightly:
  stage: test
  only:
    - schedules
  artifacts:
    name: "SiaTesting-$CI_JOB_NAME"
    paths:
      - $CI_PROJECT_DIR/SiaTesting
      - $CI_PROJECT_DIR/cover/cover.out
    when: always
  script:
    - make test-vlong pkgs="./node ./node/api ./node/api/server" run=.
    - cp -R /tmp/SiaTesting $CI_PROJECT_DIR/SiaTesting

package-tests-nightly:
  stage: test
  only:
    - schedules
  artifacts:
    name: "SiaTesting-$CI_JOB_NAME"
    paths:
      - $CI_PROJECT_DIR/SiaTesting
      - $CI_PROJECT_DIR/cover/cover.out
    when: always
  script:
    - make test-vlong run=. pkgs="./build ./cmd/spc ./cmd/spd ./compatibility ./crypto ./encoding ./modules ./modules/consensus ./modules/explorer ./modules/gateway ./modules/host ./modules/host/contractmanager ./modules/renter ./modules/renter/contractor ./modules/renter/hostdb ./modules/renter/hostdb/hosttree ./modules/renter/proto ./modules/miner ./modules/wallet ./modules/transactionpool ./persist ./sync ./types"
    - cp -R /tmp/SiaTesting $CI_PROJECT_DIR/SiaTesting

siatest-tests-nightly:
  stage: test
  only:
    - schedules
  artifacts:
    name: "SiaTesting-$CI_JOB_NAME"
    paths:
      - $CI_PROJECT_DIR/SiaTesting
      - $CI_PROJECT_DIR/cover/cover.out
    when: always
  script:
    - make test-vlong run=. pkgs="./siatest ./siatest/consensus ./siatest/daemon ./siatest/gateway ./siatest/miner ./siatest/transactionpool ./siatest/wallet"
    - cp -R /tmp/SiaTesting $CI_PROJECT_DIR/SiaTesting

siatest-renter--tests-nightly:
  stage: test
  only:
    - schedules
  artifacts:
    name: "SiaTesting-$CI_JOB_NAME"
    paths:
      - $CI_PROJECT_DIR/SiaTesting
      - $CI_PROJECT_DIR/cover/cover.out
    when: always
  script:
    - make test-vlong run=. pkgs="./siatest/renter ./siatest/renter/contractor ./siatest/renter/hostdb ./siatest/renterhost"
    - cp -R /tmp/SiaTesting $CI_PROJECT_DIR/SiaTesting

deploy:
  stage: deploy
  only:
    refs:
      - master@SiaPrime/SiaPrime
  artifacts:
    name: "Binaries"
    paths:
      - $CI_PROJECT_DIR/artifacts
  script:
    - ./deploy.sh "$NIGHTLY_SIGNING_KEY"